### ISSUE TITLE
Vault at the chest level

### ISSUE THREAD

**Issue by Slarof** [YanisBft/EnderVault#1]
If possible, I would like the **Vault** to be at the level of the chests, and not levitate :)

And so the datapack is great. Implements what the Minecraft community actively wants now, as in the same Minecraft Feedback

I hope for further updates, as well as possible datapacks using **Vault** and in other structures!

**Comment by YanisBft** [comment]
Hi! Thanks for pointing this out, it was weird indeed. The new version is uploaded on Modrinth!
Glad you like this little datapack!
